server:
  port: 8906


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}


spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    url: ${rccp.micro.datasource.url}
    username: ${rccp.micro.datasource.username}
    password: ${rccp.micro.datasource.password}
    type: ${rccp.micro.datasource.type}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1


management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

debug: true
logging:
  level:
    com.zhuj.micro.service.**.*: debug

#key
key: 5778a2910df64db1

arena:
  play:
    win: 25
    fail: 30
    consum: 100
    robotProbability: 50
    firstNum: 100


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses: http://39.107.230.45:8000/xxl-job-admin
xxl.job.accessToken:
### xxl-job executor appname
xxl.job.executor.appname: xxl-job-executor-sample
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
xxl.job.executor.address:
### xxl-job executor server-info
xxl.job.executor.ip:
xxl.job.executor.port: 9999
### xxl-job executor log-path
xxl.job.executor.logpath: ./jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays: 30

#大转盘抽奖  无地址跳转链接
ROTARY_DRAW_SKIP_DOMAIN: https://m.zhujianyun.com