server:
  port: 8801
  tomcat:
    max-http-post-size: 0
    max-http-header-size: 104857600
    #上传文件临时文件路径
    basedir: /home/temp

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
  client:
    registryFetchIntervalSeconds: 30
    fetchRegistry: true



spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    url: ${rccp.micro.datasource.url}
    username: ${rccp.micro.datasource.username}
    password: ${rccp.micro.datasource.password}
    type: ${rccp.micro.datasource.type}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  servlet:
      multipart:
        enabled: true
        max-file-size: ${rccp.micro.servlet.multipart.max-file-size}
        max-request-size: ${rccp.micro.servlet.multipart.max-request-size}
thymeleaf:
       mode: HTML5

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#-------------阿里云配置公共参数---------
#阿里云 accessKeyId
accessKeyId: LTAICZtWTxGneJgX
#阿里云 accessKeySecret
accessKeySecret: ahJozKLHA64fFQoThCJZUnIE9PFPuJ
#图片
picKey: pic
#视频
videoKey: video
#文件
fileDocKey: fileDoc
#-------------阿里云配置公共参数---------


#环境配置
endpoint: oss-cn-beijing.aliyuncs.com
endpoint2: https://oss-cn-beijing.aliyuncs.com
bucketName: rccp-dfs
#accessUrl: https://rccp-dfs.oss-cn-beijing.aliyuncs.com
accessUrl: https://rccp-dfs.oss-accelerate.aliyuncs.com/
fileUrl: http://192.168.1.89:8081
fastDfsUrl: http://192.168.1.89:8888
fastdfs:
  trackerServer: 192.168.1.89:22122
  connectTimeout: 5000
  networkTimeout: 30000
  trackerHttpPort: 8888

#线上配置
pipelineId: 261882f700fa4991aba01a6c35f0e1f0 #管道ID
location: oss-cn-beijing #输入OSS Bucket所在数据中心（OSS Location）
regionId: cn-beijing # #地域ID
templateId: 1db19c1364614bd19c94cc542c3174f5   #转码模板ID








